# Generated by Django 2.2.15 on 2020-12-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaborativa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrainfo",
            name="health_hands_where",
            field=models.CharField(
                choices=[
                    ("HCor Hospital do Coração", "HCor Hospital do Coração"),
                    ("Hospital Alemão Oswaldo Cruz", "Hospital Alemão Oswaldo Cruz"),
                    ("Hospital Israelita Albert Einstein", "Hospital Israelita Albert Einstein"),
                    ("Hospital Moinhos de Vento", "Hospital Moinhos de Vento"),
                    ("Hospital Sírio Libanês", "Hospital Sírio Libanês"),
                ],
                max_length=100,
                verbose_name="Hospital que orientou seu projeto:",
            ),
        ),
    ]
