# Generated by Django 2.2.15 on 2020-12-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaborativa", "0002_auto_20201223_2204"),
    ]

    operations = [
        migrations.RemoveField(model_name="extrainfo", name="health_hands",),
        migrations.AlterField(
            model_name="extrainfo",
            name="health_hands_where",
            field=models.CharField(
                choices=[
                    ("Não participou", "Não participou"),
                    ("HCor Hospital do Coração", "HCor Hospital do Coração"),
                    ("Hospital Alemão Oswaldo Cruz", "Hospital Alemão Oswaldo Cruz"),
                    ("Hospital Israelita Albert Einstein", "Hospital Israelita Albert Einstein"),
                    ("Hospital Moinhos de Vento", "Hospital Moinhos de Vento"),
                    ("Hospital Sírio Libanês", "Hospital Sírio Libanês"),
                ],
                max_length=100,
                verbose_name="Participa ou participou do 'Saúde em Nossas Mãos'? Se sim, selecione o hospital",
            ),
        ),
    ]
