# Generated by Django 2.2.15 on 2020-12-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaborativa", "0004_auto_20201223_2249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrainfo",
            name="health_hands_where",
            field=models.CharField(
                choices=[
                    ("Não participou", "Não participou"),
                    ("HCor Hospital do Coração", "Participou no HCor Hospital do Coração"),
                    ("Hospital Alemão Oswaldo Cruz", "Participou no Hospital Alemão Oswaldo Cruz"),
                    ("Hospital Israelita Albert Einstein", "Participou no Hospital Israelita Albert Einstein"),
                    ("Hospital Moinhos de Vento", "Participou no Hospital Moinhos de Vento"),
                    ("Hospital Sírio Libanês", "Participou no Hospital Sírio Libanês"),
                ],
                max_length=100,
                verbose_name="Participou do 'Saúde em Nossas Mãos'?",
            ),
        ),
    ]
