# Generated by Django 2.2.15 on 2020-12-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("colaborativa", "0005_auto_20201223_2253"),
    ]

    operations = [
        migrations.RemoveField(model_name="extrainfo", name="profession",),
    ]
